# Generated by Django 5.2.5 on 2026-01-25 19:32

import django.db.models.deletion
import django_quill.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('description', django_quill.fields.QuillField(blank=True, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='DailyReviewSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Time spent in hours')),
                ('daily_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reviews_skill', to='reviews.dailyreview')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reviews_skill', to='tasks.skill')),
            ],
            options={
                'unique_together': {('skill', 'daily_review')},
            },
        ),
        migrations.AddField(
            model_name='dailyreview',
            name='skills',
            field=models.ManyToManyField(related_name='daily_reviews_for_skill', through='reviews.DailyReviewSkill', to='tasks.skill'),
        ),
        migrations.CreateModel(
            name='MonthlyReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.PositiveSmallIntegerField()),
                ('goals', models.ManyToManyField(related_name='monthly_reviews_for_goal', to='tasks.goal')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', django_quill.fields.QuillField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('subgoals', models.ManyToManyField(related_name='weekly_reviews_for_subgoal', to='tasks.subgoal')),
            ],
        ),
    ]
