# Generated by Django 5.2.5 on 2026-01-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreviewskill',
            name='time_spent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Time spent in minutes'),
        ),
    ]
