# Generated by Django 5.2.5 on 2026-01-25 19:32

import django.db.models.deletion
import django_quill.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='goal name')),
                ('description', django_quill.fields.QuillField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='start date')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='deadline')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='pending', max_length=20, verbose_name='status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goal',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SubGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='subgoal name')),
                ('description', django_quill.fields.QuillField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='start date')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='deadline')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='pending', max_length=20, verbose_name='status')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgoals', to='tasks.goal')),
            ],
            options={
                'db_table': 'subgoal',
                'unique_together': {('goal', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='skill name')),
                ('description', django_quill.fields.QuillField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='start date')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='pending', max_length=20, verbose_name='status')),
                ('subgoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='tasks.subgoal')),
            ],
            options={
                'db_table': 'skill',
                'unique_together': {('subgoal', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Resource name')),
                ('url', models.URLField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tasks.skill')),
            ],
            options={
                'db_table': 'resource',
                'constraints': [models.UniqueConstraint(fields=('skill', 'name', 'url'), name='unique_resource_per_skill')],
            },
        ),
    ]
