# Generated by Django 5.2.5 on 2026-01-31 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('finished', 'Finished')], db_index=True, default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Resource name'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('finished', 'Finished')], db_index=True, default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('finished', 'Finished')], db_index=True, default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='goal_user_id_7d0af9_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['subgoal', 'status'], name='skill_subgoal_dba73c_idx'),
        ),
        migrations.AddIndex(
            model_name='subgoal',
            index=models.Index(fields=['goal', 'status'], name='subgoal_goal_id_ea47b3_idx'),
        ),
    ]
